# Generated by Django 2.2 on 2020-12-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosapp', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
