# Generated by Django 2.2 on 2020-12-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosapp', '0004_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
