# Generated by Django 2.2 on 2020-12-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosapp', '0005_remove_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='join',
            field=models.BooleanField(default=False),
        ),
    ]
